### ISSUE TITLE
Error when installing yacy

### ISSUE THREAD

**Issue by agnelvishal** [yacy/yacy_grid_mcp#39]
`sudo bash productiondeployment.sh build` completes with the below warning message 
```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /yacy_grid_mcp/src/main/java/org/json/XMLTokener.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

And I get the following errors when I run `sudo bash productiondeployment.sh run`
```

java.io.IOException: no local queue supported
        at net.yacy.grid.io.messages.PeerBroker.getConnector(PeerBroker.java:50)
        at net.yacy.grid.io.messages.PeerBroker.receive(PeerBroker.java:75)
        at net.yacy.grid.io.messages.GridBroker.receive(GridBroker.java:201)
        at net.yacy.grid.mcp.AbstractBrokerListener$QueueListener.run(AbstractBrokerListener.java:113)
2019-03-17 14:19:17.337 [Thread-1] INFO root  - Broker/Client: trying to connect to a Queue over MCP at 127.0.0.1:8100 failed
2019-03-17 14:19:17.337 [Thread-3] INFO root  - IOException: no local queue supported
java.io.IOException: no local queue supported
        at net.yacy.grid.io.messages.PeerBroker.getConnector(PeerBroker.java:50)
        at net.yacy.grid.io.messages.PeerBroker.receive(PeerBroker.java:75)
        at net.yacy.grid.io.messages.GridBroker.receive(GridBroker.java:201)
        at net.yacy.grid.mcp.AbstractBrokerListener$QueueListener.run(AbstractBrokerListener.java:113)
2019-03-17 14:19:17.337 [Thread-12] INFO root  - Broker/Client: trying to connect to a Queue over MCP at 127.0.0.1:8100 failed
2019-03-17 14:19:17.337 [Thread-12] WARN root  - Broker/Client: FATAL: connection to MCP lost! receive mcp service 'crawler', queue 'webcrawler_05
2019-03-17 14:19:17.337 [Thread-12] INFO root  - Broker/Client: receive() on peer broker/local db
2019-03-17 14:19:17.337 [Thread-1] WARN root  - Broker/Client: FATAL: connection to MCP lost! receive mcp service 'crawler', queue 'webcrawler_00
2019-03-17 14:19:17.337 [Thread-12] INFO root  - IOException: no local queue supported
java.io.IOException: no local queue supported
        at net.yacy.grid.io.messages.PeerBroker.getConnector(PeerBroker.java:50)
        at net.yacy.grid.io.messages.PeerBroker.receive(PeerBroker.java:75)
        at net.yacy.grid.io.messages.GridBroker.receive(GridBroker.java:201)
        at net.yacy.grid.mcp.AbstractBrokerListener$QueueListener.run(AbstractBrokerListener.java:113)
2019-03-17 14:19:17.337 [Thread-13] INFO root  - Broker/Client: trying to connect to a Queue over MCP at 127.0.0.1:8100 failed
2019-03-17 14:19:17.337 [Thread-13] WARN root  - Broker/Client: FATAL: connection to MCP lost! receive mcp service 'crawler', queue 'webcrawler_06
2019-03-17 14:19:17.337 [Thread-13] INFO root  - Broker/Client: receive() on peer broker/local db
2019-03-17 14:19:17.337 [Thread-1] INFO root  - Broker/Client: receive() on peer broker/local db
2019-03-17 14:19:17.337 [Thread-13] INFO root  - IOException: no local queue supported
java.io.IOException: no local queue supported
        at net.yacy.grid.io.messages.PeerBroker.getConnector(PeerBroker.java:50)
        at net.yacy.grid.io.messages.PeerBroker.receive(PeerBroker.java:75)
        at net.yacy.grid.io.messages.GridBroker.receive(GridBroker.java:201)
        at net.yacy.grid.mcp.AbstractBrokerListener$QueueListener.run(AbstractBrokerListener.java:113)
2019-03-17 14:19:17.337 [Thread-1] INFO root  - IOException: no local queue supported

```

**Comment by agnelvishal** [comment]
What should I do now? @Orbiter @praveenojha33 @nikhilrayaprolu

**Comment by agnelvishal** [comment]
When using Docker on another instance, I get the following error
```
Adding user `r' ...
Adding new group `r' (1000) ...
Adding new user `r' (1000) with group `r' ...
Creating home directory `/home/r' ...
Copying files from `/etc/skel' ...
Adding user `r' to group `sudo' ...
Adding user r to group sudo
Done.
./docker/start.sh: line 6: cd: /apache-ftpserver-1.1.0: No such file or directory
./docker/start.sh: line 7: ./bin/ftpd.sh: No such file or directory
Warning: PID file not written; -detached was passed.
[2019-03-17T18:22:33,294][INFO ][o.e.n.Node               ] [] initializing ...
[2019-03-17T18:22:33,358][INFO ][o.e.e.NodeEnvironment    ] [k73DeC4] using [1] data paths, mounts [[/ (overlay)]], net usable_space [90.1gb], net total_space [96.8gb], spins? [possibly], types [overlay]
[2019-03-17T18:22:33,358][INFO ][o.e.e.NodeEnvironment    ] [k73DeC4] heap size [1.9gb], compressed ordinary object pointers [true]
[2019-03-17T18:22:33,359][INFO ][o.e.n.Node               ] node name [k73DeC4] derived from node ID [k73DeC4DSpijEgyZ-WW2eA]; set [node.name] to override
[2019-03-17T18:22:33,360][INFO ][o.e.n.Node               ] version[5.5.0], pid[36], build[260387d/2017-06-30T23:16:05.735Z], OS[Linux/4.15.0-1032-aws/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_191/25.191-b12]
[2019-03-17T18:22:33,360][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/elasticsearch-5.5.0]
[2019-03-17T18:22:34,095][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [aggs-matrix-stats]
[2019-03-17T18:22:34,095][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [ingest-common]
[2019-03-17T18:22:34,095][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [lang-expression]
[2019-03-17T18:22:34,095][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [lang-groovy]
[2019-03-17T18:22:34,096][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [lang-mustache]
[2019-03-17T18:22:34,096][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [lang-painless]
[2019-03-17T18:22:34,096][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [parent-join]
[2019-03-17T18:22:34,096][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [percolator]
[2019-03-17T18:22:34,096][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [reindex]
[2019-03-17T18:22:34,096][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [transport-netty3]
[2019-03-17T18:22:34,097][INFO ][o.e.p.PluginsService     ] [k73DeC4] loaded module [transport-netty4]
[2019-03-17T18:22:34,097][INFO ][o.e.p.PluginsService     ] [k73DeC4] no plugins loaded
[2019-03-17T18:22:35,373][INFO ][o.e.d.DiscoveryModule    ] [k73DeC4] using discovery type [zen]
[2019-03-17T18:22:35,825][INFO ][o.e.n.Node               ] initialized
[2019-03-17T18:22:35,825][INFO ][o.e.n.Node               ] [k73DeC4] starting ...
[2019-03-17T18:22:35,952][INFO ][o.e.t.TransportService   ] [k73DeC4] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[2019-03-17T18:22:35,963][WARN ][o.e.b.BootstrapChecks    ] [k73DeC4] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
The following plugins have been enabled:
  mochiweb
  webmachine
  rabbitmq_web_dispatch
  amqp_client
  rabbitmq_management_agent
  rabbitmq_management

Applying plugin configuration to rabbit@1af0c3ba09a4...[2019-03-17T18:22:39,003][INFO ][o.e.c.s.ClusterService   ] [k73DeC4] new_master {k73DeC4}{k73DeC4DSpijEgyZ-WW2eA}{3y20SceAROui_DPQdtHObg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2019-03-17T18:22:39,020][INFO ][o.e.h.n.Netty4HttpServerTransport] [k73DeC4] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}
[2019-03-17T18:22:39,020][INFO ][o.e.n.Node               ] [k73DeC4] started
[2019-03-17T18:22:39,032][INFO ][o.e.g.GatewayService     ] [k73DeC4] recovered [0] indices into cluster_state
 started 6 plugins.
Creating user "yacygrid" ...
Setting permissions for user "yacygrid" in vhost "/" ...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
:run[2019-03-17T18:22:52,926][INFO ][o.e.c.m.MetaDataCreateIndexService] [k73DeC4] [web] creating index, cause [api], templates [], shards [1]/[1], mappings []
[2019-03-17T18:22:53,278][INFO ][o.e.c.m.MetaDataMappingService] [k73DeC4] [web/ITcOsFUdRMqdOg3WW0NZAA] create_mapping [_default_]

0 [main] INFO net.yacy.grid.mcp.Data  - Connected elasticsearch at localhost
206 [main] DEBUG net.yacy.grid.mcp.Data  - trying to connect to a Queue over MCP at 127.0.0.1:8100 failed
456 [main] DEBUG net.yacy.grid.mcp.Data  - trying to connect to a Queue over MCP at yacygrid.com:8100 failed
543 [main] INFO net.yacy.grid.mcp.Data  - Connected Broker at localhost
554 [main] DEBUG net.yacy.grid.mcp.Data  - trying to connect to the ftp server at localhost:2121 failed
554 [main] INFO net.yacy.grid.mcp.Data  - Connected to the embedded Asset Storage
556 [Thread-1] INFO net.yacy.grid.mcp.Data  - Broker Listener for service indexer, queue elasticsearch started
641 [main] INFO org.eclipse.jetty.util.log  - Logging initialized @3210ms to org.eclipse.jetty.util.log.Slf4jLog
702 [main] INFO org.eclipse.jetty.server.Server  - jetty-9.4.15.v20190215; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12
730 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - Started o.e.j.s.ServletContextHandler@21e20ad5{/,null,AVAILABLE}
739 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started httpd:8100@27a2a089{HTTP/1.1,[http/1.1]}{0.0.0.0:8100}
740 [main] INFO org.eclipse.jetty.server.Server  - Started @3309ms
740 [main] INFO net.yacy.grid.mcp.Data  - Service started at port 8100

```

**Comment by agnelvishal** [comment]
And this is the error when running `curl "127.0.0.1:8100/yacy/grid/mcp/messages/send.json?serviceName=testService&queueName=testQueue&message=hello_world"` on docker instance as well as installing by productiondeployment.sh 
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /yacy/grid/mcp/messages/send.json. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.IllegalArgumentException: No enum constant net.yacy.grid.YaCyServices.testService
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.yacy.grid.YaCyServices.valueOf(YaCyServices.java:36)
	at net.yacy.grid.mcp.api.messages.SendService.serviceImpl(SendService.java:61)
	at net.yacy.grid.http.AbstractAPIHandler.process(AbstractAPIHandler.java:101)
	at net.yacy.grid.http.AbstractAPIHandler.doGet(AbstractAPIHandler.java:83)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
</pre>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.15.v20190215</a><hr/>

</body>
</html>

```

**Comment by songproducer** [comment]
I'm also getting when I run
curl "127.0.0.1:8100/yacy/grid/mcp/messages/send.json?serviceName=testService&queueName=testQueue&message=hello_world"

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /yacy/grid/mcp/messages/send.json. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.IllegalArgumentException: No enum constant net.yacy.grid.YaCyServices.testService
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.yacy.grid.YaCyServices.valueOf(YaCyServices.java:38)
	at net.yacy.grid.mcp.api.messages.SendService.serviceImpl(SendService.java:61)
	at net.yacy.grid.http.AbstractAPIHandler.process(AbstractAPIHandler.java:120)
	at net.yacy.grid.http.AbstractAPIHandler.doGet(AbstractAPIHandler.java:100)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:876)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:745)
</pre>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.19.v20190610</a><hr/>

</body>
</html>
```
